#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Monk;
    using Monk.Areas.Backend.ViewModels;
    using Monk.Utils;
    using Monk.ViewModels;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Backend/Views/SysSet/Update.cshtml")]
    public partial class _Areas_Backend_Views_SysSet_Update_cshtml : System.Web.Mvc.WebViewPage<SysSetVM>
    {
        public _Areas_Backend_Views_SysSet_Update_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Areas\Backend\Views\SysSet\Update.cshtml"
  
    ViewBag.Title = "系统设置";
    Layout = "~/Areas/Backend/Views/Shared/_Form.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

DefineSection("head", () => {

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 8 "..\..\Areas\Backend\Views\SysSet\Update.cshtml"
Write(Styles.Render("~/Assets/Backend/WebUploader/Style"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

});

WriteLiteral("\r\n");

DefineSection("crumbs", () => {

WriteLiteral("\r\n    <label");

WriteLiteral(" class=\"backend-crumbs-separator\"");

WriteLiteral(">/</label>\r\n    <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" title=\"系统管理\"");

WriteLiteral(">系统管理</a>\r\n    <label");

WriteLiteral(" class=\"backend-crumbs-separator\"");

WriteLiteral(">/</label>\r\n    <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" title=\"系统设置\"");

WriteLiteral(">系统设置</a>\r\n    <label");

WriteLiteral(" class=\"backend-crumbs-separator\"");

WriteLiteral(">/</label>\r\n    <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" title=\"更新设置\"");

WriteLiteral(">更新设置</a>\r\n");

});

WriteLiteral("\r\n");

DefineSection("beginForm", () => {

            
            #line 20 "..\..\Areas\Backend\Views\SysSet\Update.cshtml"
                      Html.BeginForm("Update", "SysSet", FormMethod.Post, new { @class = "monk-form" });
            
            #line default
            #line hidden
});

WriteLiteral("\r\n<div");

WriteLiteral(" class=\"monk-form-item\"");

WriteLiteral(">\r\n    <label");

WriteLiteral(" for=\"Logo\"");

WriteLiteral(" class=\"monk-form-label\"");

WriteLiteral(">系统标志</label>\r\n    <div");

WriteLiteral(" class=\"monk-form-wrap noborder\"");

WriteLiteral(">\r\n        <img");

WriteAttribute("src", Tuple.Create(" src=\"", 753), Tuple.Create("\"", 770)
            
            #line 25 "..\..\Areas\Backend\Views\SysSet\Update.cshtml"
, Tuple.Create(Tuple.Create("", 759), Tuple.Create<System.Object, System.Int32>(Model.Logo
            
            #line default
            #line hidden
, 759), false)
);

WriteLiteral(" id=\"image-view\"");

WriteLiteral(" alt=\"\"");

WriteLiteral(" class=\"display-block\"");

WriteLiteral(" height=\"50\"");

WriteLiteral(" />\r\n");

WriteLiteral("        ");

            
            #line 26 "..\..\Areas\Backend\Views\SysSet\Update.cshtml"
   Write(Html.HiddenFor(u => u.Logo));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"clear-both height-8\"");

WriteLiteral("></div>\r\n    <div");

WriteLiteral(" class=\"monk-form-wrap monk-form-image-wrap\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"monk-images-selects\"");

WriteLiteral(">\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"monk-form-wrap bgcolor-white\"");

WriteLiteral(">\r\n            <span");

WriteLiteral(" class=\"monk-iconfont border-right icon-monk-input\"");

WriteLiteral("></span>\r\n            <input");

WriteLiteral(" class=\"monk-form-input normal\"");

WriteLiteral(" value=\"未选择文件\"");

WriteLiteral(" id=\"uploadUrl\"");

WriteLiteral(" readonly=\"readonly\"");

WriteLiteral(" data-src=\"");

            
            #line 34 "..\..\Areas\Backend\Views\SysSet\Update.cshtml"
                                                                                                        Write(Model.Logo);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(" />\r\n            <span");

WriteLiteral(" class=\"monk-iconfont border-left icon-monk-dacha\"");

WriteLiteral(" id=\"removeFile\"");

WriteLiteral("></span>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"monk-input-button monk-input-file\"");

WriteLiteral(" id=\"selectFiles\"");

WriteLiteral(">选择图片</div>\r\n        <div");

WriteLiteral(" class=\"monk-file-uploadProgress\"");

WriteLiteral(" id=\"uploadProgress\"");

WriteLiteral("></div>\r\n        <div");

WriteLiteral(" class=\"monk-input-button emerland\"");

WriteLiteral(" id=\"startUpload\"");

WriteLiteral(">开始上传</div>\r\n        <div");

WriteLiteral(" class=\"monk-input-button amethyst\"");

WriteLiteral(" id=\"clearUpload\"");

WriteLiteral(" disabled=\"disabled\"");

WriteLiteral(">重置删除</div>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"monk-form-tip\"");

WriteLiteral(">若成功上传并未应用，应点击 <label");

WriteLiteral(" class=\"tipcolor\"");

WriteLiteral(">重置删除</label> 按钮，服务器会删除对应文件，节省存储空间。</div>\r\n</div>\r\n<div");

WriteLiteral(" class=\"monk-form-item\"");

WriteLiteral(">\r\n    <label");

WriteLiteral(" for=\"Name\"");

WriteLiteral(" class=\"monk-form-label\"");

WriteLiteral(">系统名称</label>\r\n    <div");

WriteLiteral(" class=\"monk-form-wrap\"");

WriteLiteral(">\r\n        <span");

WriteLiteral(" class=\"monk-iconfont border-right icon-monk-input\"");

WriteLiteral("></span>\r\n");

WriteLiteral("        ");

            
            #line 48 "..\..\Areas\Backend\Views\SysSet\Update.cshtml"
   Write(Html.TextBoxFor(u => u.Name,
        new
        {
            @class = "monk-form-input normal",
            placeholder = "系统名称",
            datatype = "*1-50",
            errormsg = "系统名称由1-50位英文字母、数字或符号组成",
            nullmsg = "请输入系统名称"
        }));

            
            #line default
            #line hidden
WriteLiteral("\r\n        <span");

WriteLiteral(" class=\"monk-iconfont icon-monk-required\"");

WriteLiteral("></span>\r\n        <span");

WriteLiteral(" class=\"monk-iconfont border-left icon-monk-dacha monk-clear-input\"");

WriteLiteral("></span>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"monk-form-tip\"");

WriteLiteral(">给你的系统起个牛逼的名字吧</div>\r\n</div>\r\n<div");

WriteLiteral(" class=\"monk-form-item\"");

WriteLiteral(">\r\n    <label");

WriteLiteral(" for=\"Version\"");

WriteLiteral(" class=\"monk-form-label\"");

WriteLiteral(">系统版本</label>\r\n    <div");

WriteLiteral(" class=\"monk-form-wrap\"");

WriteLiteral(">\r\n        <span");

WriteLiteral(" class=\"monk-iconfont border-right icon-monk-input\"");

WriteLiteral("></span>\r\n");

WriteLiteral("        ");

            
            #line 66 "..\..\Areas\Backend\Views\SysSet\Update.cshtml"
   Write(Html.TextBoxFor(u => u.Version,
        new
        {
            @class = "monk-form-input middle",
            placeholder = "系统版本",
            datatype = "*1-25",
            errormsg = "系统版本由1-25位英文字母、数字或符号组成",
            nullmsg = "请输入系统版本"
        }));

            
            #line default
            #line hidden
WriteLiteral("\r\n        <span");

WriteLiteral(" class=\"monk-iconfont icon-monk-required\"");

WriteLiteral("></span>\r\n        <span");

WriteLiteral(" class=\"monk-iconfont border-left icon-monk-dacha monk-clear-input\"");

WriteLiteral("></span>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"monk-form-tip\"");

WriteLiteral(">通常系统版本格式为：v1.0.0</div>\r\n</div>\r\n<div");

WriteLiteral(" class=\"monk-form-item\"");

WriteLiteral(">\r\n    <label");

WriteLiteral(" for=\"Keywords\"");

WriteLiteral(" class=\"monk-form-label\"");

WriteLiteral(">关键字</label>\r\n    <div");

WriteLiteral(" class=\"monk-form-wrap\"");

WriteLiteral(">\r\n        <span");

WriteLiteral(" class=\"monk-iconfont border-right icon-monk-input textarea-icon\"");

WriteLiteral("></span>\r\n");

WriteLiteral("        ");

            
            #line 84 "..\..\Areas\Backend\Views\SysSet\Update.cshtml"
   Write(Html.TextAreaFor(u => u.Keywords,
        new
        {
            @class = "monk-form-textarea normal",
            placeholder = "关键字",
            datatype = "*1-100",
            ignore = "ignore",
            errormsg = "关键字由1-100位英文字母、数字或符号组成",
            nullmsg = "请输入关键字"
        }));

            
            #line default
            #line hidden
WriteLiteral("\r\n        <span");

WriteLiteral(" class=\"monk-iconfont border-left icon-monk-dacha monk-clear-input textarea-icon\"" +
"");

WriteLiteral("></span>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"monk-form-tip\"");

WriteLiteral(">SEO关键字，用英文逗号隔开，方法搜索引擎收录</div>\r\n</div>\r\n<div");

WriteLiteral(" class=\"monk-form-item\"");

WriteLiteral(">\r\n    <label");

WriteLiteral(" for=\"Description\"");

WriteLiteral(" class=\"monk-form-label\"");

WriteLiteral(">系统描述</label>\r\n    <div");

WriteLiteral(" class=\"monk-form-wrap\"");

WriteLiteral(">\r\n        <span");

WriteLiteral(" class=\"monk-iconfont border-right icon-monk-input textarea-icon\"");

WriteLiteral("></span>\r\n");

WriteLiteral("        ");

            
            #line 102 "..\..\Areas\Backend\Views\SysSet\Update.cshtml"
   Write(Html.TextAreaFor(u => u.Description,
        new
        {
            @class = "monk-form-textarea normal",
            placeholder = "系统描述",
            datatype = "*1-160",
            ignore = "ignore",
            errormsg = "系统描述由1-160位英文字母、数字或符号组成",
            nullmsg = "请输入系统描述"
        }));

            
            #line default
            #line hidden
WriteLiteral("\r\n        <span");

WriteLiteral(" class=\"monk-iconfont border-left icon-monk-dacha monk-clear-input textarea-icon\"" +
"");

WriteLiteral("></span>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"monk-form-tip\"");

WriteLiteral(">简单一句话，描述一下该系统吧。</div>\r\n</div>\r\n<div");

WriteLiteral(" class=\"monk-form-item\"");

WriteLiteral(">\r\n    <label");

WriteLiteral(" for=\"Support\"");

WriteLiteral(" class=\"monk-form-label\"");

WriteLiteral(">技术支持</label>\r\n    <div");

WriteLiteral(" class=\"monk-form-wrap\"");

WriteLiteral(">\r\n        <span");

WriteLiteral(" class=\"monk-iconfont border-right icon-monk-input\"");

WriteLiteral("></span>\r\n");

WriteLiteral("        ");

            
            #line 120 "..\..\Areas\Backend\Views\SysSet\Update.cshtml"
   Write(Html.TextBoxFor(u => u.Support,
        new
        {
            @class = "monk-form-input normal",
            disabled = "disabled",
            placeholder = "技术支持",
            ignore = "ignore",
            datatype = "*1-50",
            errormsg = "技术支持由1-50位英文字母、数字或符号组成",
            nullmsg = "请输入技术支持"
        }));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"monk-form-tip\"");

WriteLiteral(">毋庸置疑，只有创造她的人才更懂她~~</div>\r\n</div>\r\n<div");

WriteLiteral(" class=\"monk-form-item\"");

WriteLiteral(">\r\n    <label");

WriteLiteral(" for=\"CopyRight\"");

WriteLiteral(" class=\"monk-form-label\"");

WriteLiteral(">版权所有</label>\r\n    <div");

WriteLiteral(" class=\"monk-form-wrap\"");

WriteLiteral(">\r\n        <span");

WriteLiteral(" class=\"monk-iconfont border-right icon-monk-input textarea-icon\"");

WriteLiteral("></span>\r\n");

WriteLiteral("        ");

            
            #line 138 "..\..\Areas\Backend\Views\SysSet\Update.cshtml"
   Write(Html.TextAreaFor(u => u.CopyRight,
        new
        {
            @class = "monk-form-textarea normal",
            placeholder = "版权所有",
            datatype = "*1-100",
            ignore = "ignore",
            errormsg = "版权所有由1-100位英文字母、数字或符号组成",
            nullmsg = "请输入版权所有"
        }));

            
            #line default
            #line hidden
WriteLiteral("\r\n        <span");

WriteLiteral(" class=\"monk-iconfont border-left icon-monk-dacha monk-clear-input textarea-icon\"" +
"");

WriteLiteral("></span>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"monk-form-tip\"");

WriteLiteral(">格式通常为：Copyright ©  2016 百签软件（中山）有限公司. All rights reserved.</div>\r\n</div>\r\n<div");

WriteLiteral(" class=\"monk-form-item\"");

WriteLiteral(">\r\n    <label");

WriteLiteral(" for=\"Site\"");

WriteLiteral(" class=\"monk-form-label\"");

WriteLiteral(">官方网址</label>\r\n    <div");

WriteLiteral(" class=\"monk-form-wrap\"");

WriteLiteral(">\r\n        <span");

WriteLiteral(" class=\"monk-iconfont border-right icon-monk-input\"");

WriteLiteral("></span>\r\n");

WriteLiteral("        ");

            
            #line 156 "..\..\Areas\Backend\Views\SysSet\Update.cshtml"
   Write(Html.TextBoxFor(u => u.Site,
        new
        {
            @class = "monk-form-input normal",
            placeholder = "官方网址",
            datatype = "url",
            ignore = "ignore",
            errormsg = "请输入正确的网址",
            nullmsg = "请输入官方网址"
        }));

            
            #line default
            #line hidden
WriteLiteral("\r\n        <span");

WriteLiteral(" class=\"monk-iconfont border-left icon-monk-dacha monk-clear-input\"");

WriteLiteral("></span>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"monk-form-tip\"");

WriteLiteral(">写下你的官方网址，让大家多了解一下你。</div>\r\n</div>\r\n<div");

WriteLiteral(" class=\"monk-form-item\"");

WriteLiteral(">\r\n    <label");

WriteLiteral(" for=\"PageSize\"");

WriteLiteral(" class=\"monk-form-label\"");

WriteLiteral(">默认页容量</label>\r\n    <div");

WriteLiteral(" class=\"monk-form-wrap\"");

WriteLiteral(">\r\n        <span");

WriteLiteral(" class=\"monk-iconfont border-right icon-monk-input\"");

WriteLiteral("></span>\r\n");

WriteLiteral("        ");

            
            #line 174 "..\..\Areas\Backend\Views\SysSet\Update.cshtml"
   Write(Html.TextBoxFor(u => u.PageSize,
        new
        {
            @class = "monk-form-input min",
            placeholder = "默认页容量",
            datatype = "n",
            errormsg = "页容量必须是正整数",
            nullmsg = "请输入默认页容量"
        }));

            
            #line default
            #line hidden
WriteLiteral("\r\n        <span");

WriteLiteral(" class=\"monk-iconfont icon-monk-required\"");

WriteLiteral("></span>\r\n        <span");

WriteLiteral(" class=\"monk-iconfont border-left icon-monk-dacha monk-clear-input\"");

WriteLiteral("></span>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"monk-form-tip\"");

WriteLiteral(">指定一下默认的数据显示条数吧</div>\r\n</div>\r\n<div");

WriteLiteral(" class=\"monk-form-item\"");

WriteLiteral(">\r\n    <label");

WriteLiteral(" for=\"ImageMaxSize\"");

WriteLiteral(" class=\"monk-form-label\"");

WriteLiteral(">图片最大上传大小（M）</label>\r\n    <div");

WriteLiteral(" class=\"monk-form-wrap\"");

WriteLiteral(">\r\n        <span");

WriteLiteral(" class=\"monk-iconfont border-right icon-monk-input\"");

WriteLiteral("></span>\r\n");

WriteLiteral("        ");

            
            #line 192 "..\..\Areas\Backend\Views\SysSet\Update.cshtml"
   Write(Html.TextBoxFor(u => u.ImageMaxSize,
        new
        {
            @class = "monk-form-input min",
            placeholder = "图片最大上传大小（M）",
            datatype = "n",
            errormsg = "只能输入正整数",
            nullmsg = "请输入图片最大上传大小（M）"
        }));

            
            #line default
            #line hidden
WriteLiteral("\r\n        <span");

WriteLiteral(" class=\"monk-iconfont icon-monk-required\"");

WriteLiteral("></span>\r\n        <span");

WriteLiteral(" class=\"monk-iconfont border-left icon-monk-dacha monk-clear-input\"");

WriteLiteral("></span>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"monk-form-tip\"");

WriteLiteral(">指定该数值可以显示用户上传图片的大小</div>\r\n</div>\r\n<div");

WriteLiteral(" class=\"monk-form-item\"");

WriteLiteral(">\r\n    <label");

WriteLiteral(" for=\"VideoMaxSize\"");

WriteLiteral(" class=\"monk-form-label\"");

WriteLiteral(">视频最大上传大小（M）</label>\r\n    <div");

WriteLiteral(" class=\"monk-form-wrap\"");

WriteLiteral(">\r\n        <span");

WriteLiteral(" class=\"monk-iconfont border-right icon-monk-input\"");

WriteLiteral("></span>\r\n");

WriteLiteral("        ");

            
            #line 210 "..\..\Areas\Backend\Views\SysSet\Update.cshtml"
   Write(Html.TextBoxFor(u => u.VideoMaxSize,
        new
        {
            @class = "monk-form-input min",
            placeholder = "视频最大上传大小（M）",
            datatype = "n",
            errormsg = "只能输入正整数",
            nullmsg = "请输入视频最大上传大小（M）"
        }));

            
            #line default
            #line hidden
WriteLiteral("\r\n        <span");

WriteLiteral(" class=\"monk-iconfont icon-monk-required\"");

WriteLiteral("></span>\r\n        <span");

WriteLiteral(" class=\"monk-iconfont border-left icon-monk-dacha monk-clear-input\"");

WriteLiteral("></span>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"monk-form-tip\"");

WriteLiteral(">指定该数值可以显示用户上传视频的大小</div>\r\n</div>\r\n<div");

WriteLiteral(" class=\"monk-form-item\"");

WriteLiteral(">\r\n    <label");

WriteLiteral(" for=\"AttachMaxSize\"");

WriteLiteral(" class=\"monk-form-label\"");

WriteLiteral(">附件最大上传大小（M）</label>\r\n    <div");

WriteLiteral(" class=\"monk-form-wrap\"");

WriteLiteral(">\r\n        <span");

WriteLiteral(" class=\"monk-iconfont border-right icon-monk-input\"");

WriteLiteral("></span>\r\n");

WriteLiteral("        ");

            
            #line 228 "..\..\Areas\Backend\Views\SysSet\Update.cshtml"
   Write(Html.TextBoxFor(u => u.AttachMaxSize,
        new
        {
            @class = "monk-form-input min",
            placeholder = "附件最大上传大小（M）",
            datatype = "n",
            errormsg = "只能输入正整数",
            nullmsg = "请输入附件最大上传大小（M）"
        }));

            
            #line default
            #line hidden
WriteLiteral("\r\n        <span");

WriteLiteral(" class=\"monk-iconfont icon-monk-required\"");

WriteLiteral("></span>\r\n        <span");

WriteLiteral(" class=\"monk-iconfont border-left icon-monk-dacha monk-clear-input\"");

WriteLiteral("></span>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"monk-form-tip\"");

WriteLiteral(">指定该数值可以显示用户上传附件的大小</div>\r\n</div>\r\n\r\n\r\n");

DefineSection("operate", () => {

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 245 "..\..\Areas\Backend\Views\SysSet\Update.cshtml"
Write(Html.HiddenFor(u => u.SetID));

            
            #line default
            #line hidden
WriteLiteral("\r\n    <input");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"monk-input-button turquoise monk-form-submit\"");

WriteLiteral(" value=\"提交保存\"");

WriteLiteral(">\r\n    <input");

WriteLiteral(" type=\"reset\"");

WriteLiteral(" class=\"monk-input-button amethyst monk-form-reset\"");

WriteLiteral(" value=\"重置表单\"");

WriteLiteral(">\r\n    <input");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"monk-input-button orange monk-form-previous\"");

WriteLiteral(" value=\"返回前页\"");

WriteLiteral(" onclick=\"history.go(-1);\"");

WriteLiteral(">\r\n");

});

WriteLiteral("\r\n");

DefineSection("endForm", () => {

            
            #line 251 "..\..\Areas\Backend\Views\SysSet\Update.cshtml"
                    Html.EndForm();
            
            #line default
            #line hidden
});

WriteLiteral("\r\n");

DefineSection("foot", () => {

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 254 "..\..\Areas\Backend\Views\SysSet\Update.cshtml"
Write(Scripts.Render("~/Assets/Backend/WebUploader/Script"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n        $(function () {\r\n            var src= $(\"#uploadUrl\").attr(\"data-src\")" +
";\r\n            // 图片上传\r\n            var uploader = backend.fileUpload({\r\n       " +
"         options: {\r\n                    fileSingleSizeLimit : ");

            
            #line 261 "..\..\Areas\Backend\Views\SysSet\Update.cshtml"
                                     Write(ViewBag.SysSetInfo.ImageMaxSize);

            
            #line default
            #line hidden
WriteLiteral(" * 1024 * 1024\r\n                },\r\n                data:{\r\n                    a" +
"rea:\"");

            
            #line 264 "..\..\Areas\Backend\Views\SysSet\Update.cshtml"
                     Write(ViewContext.RouteData.DataTokens["area"]);

            
            #line default
            #line hidden
WriteLiteral("\",\r\n                    controller:\"");

            
            #line 265 "..\..\Areas\Backend\Views\SysSet\Update.cshtml"
                           Write(ViewContext.RouteData.Values["controller"]);

            
            #line default
            #line hidden
WriteLiteral(@"""
                },
                fileDequeued:function(file){
                    $(""#image-view"").attr(""src"",src);
                    $(""#Logo"").val(src);
                },
                uploadSuccess:function(file,response){
                    $(""#image-view"").attr(""src"",response.data.path);
                    $(""#Logo"").val(response.data.path);
                }
            });

            backend.validform(function (data) {
                window.location.href=""");

            
            #line 278 "..\..\Areas\Backend\Views\SysSet\Update.cshtml"
                                 Write(Url.Action("Detail","SysSet"));

            
            #line default
            #line hidden
WriteLiteral("\";\r\n            });\r\n        });\r\n    </script>\r\n");

});

        }
    }
}
#pragma warning restore 1591
