#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Monk;
    using Monk.Utils;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Forum/Views/Shared/_Layout.cshtml")]
    public partial class _Areas_Forum_Views_Shared__Layout_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Areas_Forum_Views_Shared__Layout_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<!DOCTYPE html>\r\n<html>\r\n<head>\r\n    <meta");

WriteLiteral(" charset=\"utf-8\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" http-equiv=\"Content-Type\"");

WriteLiteral(" content=\"text/html; charset=utf-8\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" http-equiv=\"X-UA-Compatible\"");

WriteLiteral(" content=\"IE=Edge,chrome=1\"");

WriteLiteral(">\r\n    <meta");

WriteLiteral(" name=\"renderer\"");

WriteLiteral(" content=\"webkit\"");

WriteLiteral(">\r\n    <title>");

            
            #line 8 "..\..\Areas\Forum\Views\Shared\_Layout.cshtml"
      Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral("</title>\r\n    <meta");

WriteLiteral(" name=\"author\"");

WriteLiteral(" content=\"百签软件有限公司,百小僧\"");

WriteLiteral(">\r\n    <meta");

WriteLiteral(" name=\"generator\"");

WriteLiteral(" content=\"Visual Studio\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" name=\"keywords\"");

WriteAttribute("content", Tuple.Create(" content=\"", 415), Tuple.Create("\"", 444)
            
            #line 11 "..\..\Areas\Forum\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 425), Tuple.Create<System.Object, System.Int32>(ViewBag.Keywords
            
            #line default
            #line hidden
, 425), false)
);

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" name=\"description\"");

WriteAttribute("content", Tuple.Create(" content=\"", 478), Tuple.Create("\"", 510)
            
            #line 12 "..\..\Areas\Forum\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 488), Tuple.Create<System.Object, System.Int32>(ViewBag.Description
            
            #line default
            #line hidden
, 488), false)
);

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" name=\"copyright\"");

WriteAttribute("content", Tuple.Create(" content=\"", 542), Tuple.Create("\"", 572)
            
            #line 13 "..\..\Areas\Forum\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 552), Tuple.Create<System.Object, System.Int32>(ViewBag.Copyright
            
            #line default
            #line hidden
, 552), false)
);

WriteLiteral(" />\r\n    <link");

WriteLiteral(" rel=\"shortcut icon\"");

WriteAttribute("href", Tuple.Create(" href=\"", 607), Tuple.Create("\"", 646)
, Tuple.Create(Tuple.Create("", 614), Tuple.Create<System.Object, System.Int32>(Href("~/Areas/Forum/Assets/favicon.ico")
, 614), false)
);

WriteLiteral(" />\r\n");

WriteLiteral("    ");

            
            #line 15 "..\..\Areas\Forum\Views\Shared\_Layout.cshtml"
Write(Styles.Render("~/Assets/Forum/Style"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 16 "..\..\Areas\Forum\Views\Shared\_Layout.cshtml"
Write(RenderSection("head", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n</head>\r\n<body ");

            
            #line 18 "..\..\Areas\Forum\Views\Shared\_Layout.cshtml"
 Write(RenderSection("bodyAttr", false));

            
            #line default
            #line hidden
WriteLiteral(">\r\n");

WriteLiteral("    ");

            
            #line 19 "..\..\Areas\Forum\Views\Shared\_Layout.cshtml"
Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 20 "..\..\Areas\Forum\Views\Shared\_Layout.cshtml"
Write(Scripts.Render("~/Assets/Forum/Script"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 21 "..\..\Areas\Forum\Views\Shared\_Layout.cshtml"
Write(RenderSection("foot", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n</body>\r\n</html>\r\n");

        }
    }
}
#pragma warning restore 1591
