#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Monk;
    using Monk.Utils;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Forum/Views/Default/Index.cshtml")]
    public partial class _Areas_Forum_Views_Default_Index_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Areas_Forum_Views_Default_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Areas\Forum\Views\Default\Index.cshtml"
  
    ViewBag.Title = "社区首页";
    Layout = "~/Areas/Forum/Views/Shared/_Layout.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" id=\"forum-top\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"forum-wrapper\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" id=\"forum-logo\"");

WriteLiteral(" class=\"forum-float-left\"");

WriteLiteral(">\r\n            <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" title=\"\"");

WriteLiteral(" class=\"display-block\"");

WriteLiteral("><img");

WriteAttribute("src", Tuple.Create(" src=\"", 267), Tuple.Create("\"", 315)
, Tuple.Create(Tuple.Create("", 273), Tuple.Create<System.Object, System.Int32>(Href("~/Areas/Forum/Assets/Images/forum-logo.png")
, 273), false)
);

WriteLiteral(" alt=\"\"");

WriteLiteral(" title=\"\"");

WriteLiteral(" class=\"forum-display-block\"");

WriteLiteral(" /></a>\r\n        </div>\r\n        <div");

WriteLiteral(" id=\"forum-top-search\"");

WriteLiteral(" class=\"forum-float-left\"");

WriteLiteral(">\r\n            <span");

WriteLiteral(" class=\"forum-iconfont icon-forum-search\"");

WriteLiteral("></span>\r\n            <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"forum-top-search-input\"");

WriteLiteral(" placeholder=\"输入关键字搜索...\"");

WriteLiteral(" />\r\n        </div>\r\n        <div");

WriteLiteral(" id=\"forum-top-nav\"");

WriteLiteral(" class=\"forum-float-right\"");

WriteLiteral(">\r\n            <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" title=\"#\"");

WriteLiteral(">首页</a>\r\n            <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" title=\"#\"");

WriteLiteral(">登录</a>\r\n            <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" title=\"#\"");

WriteLiteral(">注册</a>\r\n            <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" title=\"#\"");

WriteLiteral(">关于</a>\r\n            <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" title=\"#\"");

WriteLiteral(">百签软件</a>\r\n        </div>\r\n    </div>\r\n</div>\r\n<div");

WriteLiteral(" id=\"forum-container\"");

WriteLiteral(" class=\"forum-clear-both forum-auto-height\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"forum-wrapper\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" id=\"forum-articles\"");

WriteLiteral(" class=\"forum-float-left\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" id=\"forum-article-classify\"");

WriteLiteral(">\r\n                <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"selected\"");

WriteLiteral(">全部</a>\r\n                <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">最新发表</a>\r\n                <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">抢沙发</a>\r\n                <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">精华帖子</a>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"forum-article-list forum-clear-both\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"forum-article-item forum-clear-both forum-auto-height\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"forum-article-member forum-float-left\"");

WriteLiteral(">\r\n                        <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" title=\"\"");

WriteLiteral(" class=\"forum-display-block\"");

WriteLiteral("><img");

WriteAttribute("src", Tuple.Create(" src=\"", 1625), Tuple.Create("\"", 1674)
, Tuple.Create(Tuple.Create("", 1631), Tuple.Create<System.Object, System.Int32>(Href("~/Areas/Forum/Assets/Images/default-pic.jpg")
, 1631), false)
);

WriteLiteral(" alt=\"\"");

WriteLiteral(" title=\"\"");

WriteLiteral(" class=\"forum-display-block\"");

WriteLiteral(" /></a>\r\n                    </div>\r\n                    <div");

WriteLiteral(" class=\"forum-article-props forum-float-left\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"forum-article-title\"");

WriteLiteral(">\r\n                            <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" title=\"#\"");

WriteLiteral(" class=\"forum-item-classify\"");

WriteLiteral(">[技术分享]</a>\r\n                            <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" title=\"#\"");

WriteLiteral(" class=\"forum-item-title\"");

WriteLiteral(">百签软件（中山）有限公司国庆放假消息。</a>\r\n                        </div>\r\n                       " +
" <div");

WriteLiteral(" class=\"forum-article-pushinfo forum-clear-both\"");

WriteLiteral(">\r\n                            <span");

WriteLiteral(" class=\"forum-article-tip\"");

WriteLiteral(">发布者：</span><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"forum-article-info\"");

WriteLiteral(">百小僧</a> <span");

WriteLiteral(" class=\"forum-article-tip\"");

WriteLiteral(">2016-09-22，最后回复来自：</span><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"forum-article-info\"");

WriteLiteral(">百签软件</a>\r\n                            <div");

WriteLiteral(" class=\"forum-article-record forum-float-right\"");

WriteLiteral("><span");

WriteLiteral(" class=\"forum-iconfont icon-forum-chakan\"");

WriteLiteral(">9</span><span");

WriteLiteral(" class=\"forum-iconfont icon-forum-pinglun\"");

WriteLiteral(">5</span></div>\r\n                        </div>\r\n                    </div>\r\n    " +
"            </div>\r\n                <div");

WriteLiteral(" class=\"forum-article-item forum-clear-both forum-auto-height\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"forum-article-member forum-float-left\"");

WriteLiteral(">\r\n                        <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" title=\"\"");

WriteLiteral(" class=\"forum-display-block\"");

WriteLiteral("><img");

WriteAttribute("src", Tuple.Create(" src=\"", 2930), Tuple.Create("\"", 2979)
, Tuple.Create(Tuple.Create("", 2936), Tuple.Create<System.Object, System.Int32>(Href("~/Areas/Forum/Assets/Images/default-pic.jpg")
, 2936), false)
);

WriteLiteral(" alt=\"\"");

WriteLiteral(" title=\"\"");

WriteLiteral(" class=\"forum-display-block\"");

WriteLiteral(" /></a>\r\n                    </div>\r\n                    <div");

WriteLiteral(" class=\"forum-article-props forum-float-left\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"forum-article-title\"");

WriteLiteral(">\r\n                            <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" title=\"#\"");

WriteLiteral(" class=\"forum-item-classify\"");

WriteLiteral(">[技术分享]</a>\r\n                            <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" title=\"#\"");

WriteLiteral(" class=\"forum-item-title\"");

WriteLiteral(">百签软件（中山）有限公司国庆放假消息。</a>\r\n                        </div>\r\n                       " +
" <div");

WriteLiteral(" class=\"forum-article-pushinfo forum-clear-both\"");

WriteLiteral(">\r\n                            <span");

WriteLiteral(" class=\"forum-article-tip\"");

WriteLiteral(">发布者：</span><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"forum-article-info\"");

WriteLiteral(">百小僧</a> <span");

WriteLiteral(" class=\"forum-article-tip\"");

WriteLiteral(">2016-09-22，最后回复来自：</span><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"forum-article-info\"");

WriteLiteral(">百签软件</a>\r\n                            <div");

WriteLiteral(" class=\"forum-article-record forum-float-right\"");

WriteLiteral("><span");

WriteLiteral(" class=\"forum-iconfont icon-forum-chakan\"");

WriteLiteral(">9</span><span");

WriteLiteral(" class=\"forum-iconfont icon-forum-pinglun\"");

WriteLiteral(">5</span></div>\r\n                        </div>\r\n                    </div>\r\n    " +
"            </div>\r\n                <div");

WriteLiteral(" class=\"forum-article-item forum-clear-both forum-auto-height\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"forum-article-member forum-float-left\"");

WriteLiteral(">\r\n                        <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" title=\"\"");

WriteLiteral(" class=\"forum-display-block\"");

WriteLiteral("><img");

WriteAttribute("src", Tuple.Create(" src=\"", 4235), Tuple.Create("\"", 4284)
, Tuple.Create(Tuple.Create("", 4241), Tuple.Create<System.Object, System.Int32>(Href("~/Areas/Forum/Assets/Images/default-pic.jpg")
, 4241), false)
);

WriteLiteral(" alt=\"\"");

WriteLiteral(" title=\"\"");

WriteLiteral(" class=\"forum-display-block\"");

WriteLiteral(" /></a>\r\n                    </div>\r\n                    <div");

WriteLiteral(" class=\"forum-article-props forum-float-left\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"forum-article-title\"");

WriteLiteral(">\r\n                            <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" title=\"#\"");

WriteLiteral(" class=\"forum-item-classify\"");

WriteLiteral(">[技术分享]</a>\r\n                            <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" title=\"#\"");

WriteLiteral(" class=\"forum-item-title\"");

WriteLiteral(">百签软件（中山）有限公司国庆放假消息。</a>\r\n                        </div>\r\n                       " +
" <div");

WriteLiteral(" class=\"forum-article-pushinfo forum-clear-both\"");

WriteLiteral(">\r\n                            <span");

WriteLiteral(" class=\"forum-article-tip\"");

WriteLiteral(">发布者：</span><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"forum-article-info\"");

WriteLiteral(">百小僧</a> <span");

WriteLiteral(" class=\"forum-article-tip\"");

WriteLiteral(">2016-09-22，最后回复来自：</span><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"forum-article-info\"");

WriteLiteral(">百签软件</a>\r\n                            <div");

WriteLiteral(" class=\"forum-article-record forum-float-right\"");

WriteLiteral("><span");

WriteLiteral(" class=\"forum-iconfont icon-forum-chakan\"");

WriteLiteral(">9</span><span");

WriteLiteral(" class=\"forum-iconfont icon-forum-pinglun\"");

WriteLiteral(">5</span></div>\r\n                        </div>\r\n                    </div>\r\n    " +
"            </div>\r\n                <div");

WriteLiteral(" class=\"forum-article-item forum-clear-both forum-auto-height\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"forum-article-member forum-float-left\"");

WriteLiteral(">\r\n                        <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" title=\"\"");

WriteLiteral(" class=\"forum-display-block\"");

WriteLiteral("><img");

WriteAttribute("src", Tuple.Create(" src=\"", 5540), Tuple.Create("\"", 5589)
, Tuple.Create(Tuple.Create("", 5546), Tuple.Create<System.Object, System.Int32>(Href("~/Areas/Forum/Assets/Images/default-pic.jpg")
, 5546), false)
);

WriteLiteral(" alt=\"\"");

WriteLiteral(" title=\"\"");

WriteLiteral(" class=\"forum-display-block\"");

WriteLiteral(" /></a>\r\n                    </div>\r\n                    <div");

WriteLiteral(" class=\"forum-article-props forum-float-left\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"forum-article-title\"");

WriteLiteral(">\r\n                            <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" title=\"#\"");

WriteLiteral(" class=\"forum-item-classify\"");

WriteLiteral(">[技术分享]</a>\r\n                            <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" title=\"#\"");

WriteLiteral(" class=\"forum-item-title\"");

WriteLiteral(">百签软件（中山）有限公司国庆放假消息。</a>\r\n                        </div>\r\n                       " +
" <div");

WriteLiteral(" class=\"forum-article-pushinfo forum-clear-both\"");

WriteLiteral(">\r\n                            <span");

WriteLiteral(" class=\"forum-article-tip\"");

WriteLiteral(">发布者：</span><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"forum-article-info\"");

WriteLiteral(">百小僧</a> <span");

WriteLiteral(" class=\"forum-article-tip\"");

WriteLiteral(">2016-09-22，最后回复来自：</span><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"forum-article-info\"");

WriteLiteral(">百签软件</a>\r\n                            <div");

WriteLiteral(" class=\"forum-article-record forum-float-right\"");

WriteLiteral("><span");

WriteLiteral(" class=\"forum-iconfont icon-forum-chakan\"");

WriteLiteral(">9</span><span");

WriteLiteral(" class=\"forum-iconfont icon-forum-pinglun\"");

WriteLiteral(">5</span></div>\r\n                        </div>\r\n                    </div>\r\n    " +
"            </div>\r\n                <div");

WriteLiteral(" class=\"forum-article-item forum-clear-both forum-auto-height\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"forum-article-member forum-float-left\"");

WriteLiteral(">\r\n                        <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" title=\"\"");

WriteLiteral(" class=\"forum-display-block\"");

WriteLiteral("><img");

WriteAttribute("src", Tuple.Create(" src=\"", 6845), Tuple.Create("\"", 6894)
, Tuple.Create(Tuple.Create("", 6851), Tuple.Create<System.Object, System.Int32>(Href("~/Areas/Forum/Assets/Images/default-pic.jpg")
, 6851), false)
);

WriteLiteral(" alt=\"\"");

WriteLiteral(" title=\"\"");

WriteLiteral(" class=\"forum-display-block\"");

WriteLiteral(" /></a>\r\n                    </div>\r\n                    <div");

WriteLiteral(" class=\"forum-article-props forum-float-left\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"forum-article-title\"");

WriteLiteral(">\r\n                            <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" title=\"#\"");

WriteLiteral(" class=\"forum-item-classify\"");

WriteLiteral(">[技术分享]</a>\r\n                            <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" title=\"#\"");

WriteLiteral(" class=\"forum-item-title\"");

WriteLiteral(">百签软件（中山）有限公司国庆放假消息。</a>\r\n                        </div>\r\n                       " +
" <div");

WriteLiteral(" class=\"forum-article-pushinfo forum-clear-both\"");

WriteLiteral(">\r\n                            <span");

WriteLiteral(" class=\"forum-article-tip\"");

WriteLiteral(">发布者：</span><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"forum-article-info\"");

WriteLiteral(">百小僧</a> <span");

WriteLiteral(" class=\"forum-article-tip\"");

WriteLiteral(">2016-09-22，最后回复来自：</span><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"forum-article-info\"");

WriteLiteral(">百签软件</a>\r\n                            <div");

WriteLiteral(" class=\"forum-article-record forum-float-right\"");

WriteLiteral("><span");

WriteLiteral(" class=\"forum-iconfont icon-forum-chakan\"");

WriteLiteral(">9</span><span");

WriteLiteral(" class=\"forum-iconfont icon-forum-pinglun\"");

WriteLiteral(">5</span></div>\r\n                        </div>\r\n                    </div>\r\n    " +
"            </div>\r\n                <div");

WriteLiteral(" class=\"forum-article-item forum-clear-both forum-auto-height\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"forum-article-member forum-float-left\"");

WriteLiteral(">\r\n                        <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" title=\"\"");

WriteLiteral(" class=\"forum-display-block\"");

WriteLiteral("><img");

WriteAttribute("src", Tuple.Create(" src=\"", 8150), Tuple.Create("\"", 8199)
, Tuple.Create(Tuple.Create("", 8156), Tuple.Create<System.Object, System.Int32>(Href("~/Areas/Forum/Assets/Images/default-pic.jpg")
, 8156), false)
);

WriteLiteral(" alt=\"\"");

WriteLiteral(" title=\"\"");

WriteLiteral(" class=\"forum-display-block\"");

WriteLiteral(" /></a>\r\n                    </div>\r\n                    <div");

WriteLiteral(" class=\"forum-article-props forum-float-left\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"forum-article-title\"");

WriteLiteral(">\r\n                            <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" title=\"#\"");

WriteLiteral(" class=\"forum-item-classify\"");

WriteLiteral(">[技术分享]</a>\r\n                            <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" title=\"#\"");

WriteLiteral(" class=\"forum-item-title\"");

WriteLiteral(">百签软件（中山）有限公司国庆放假消息。</a>\r\n                        </div>\r\n                       " +
" <div");

WriteLiteral(" class=\"forum-article-pushinfo forum-clear-both\"");

WriteLiteral(">\r\n                            <span");

WriteLiteral(" class=\"forum-article-tip\"");

WriteLiteral(">发布者：</span><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"forum-article-info\"");

WriteLiteral(">百小僧</a> <span");

WriteLiteral(" class=\"forum-article-tip\"");

WriteLiteral(">2016-09-22，最后回复来自：</span><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"forum-article-info\"");

WriteLiteral(">百签软件</a>\r\n                            <div");

WriteLiteral(" class=\"forum-article-record forum-float-right\"");

WriteLiteral("><span");

WriteLiteral(" class=\"forum-iconfont icon-forum-chakan\"");

WriteLiteral(">9</span><span");

WriteLiteral(" class=\"forum-iconfont icon-forum-pinglun\"");

WriteLiteral(">5</span></div>\r\n                        </div>\r\n                    </div>\r\n    " +
"            </div>\r\n                <div");

WriteLiteral(" class=\"forum-article-item forum-clear-both forum-auto-height\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"forum-article-member forum-float-left\"");

WriteLiteral(">\r\n                        <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" title=\"\"");

WriteLiteral(" class=\"forum-display-block\"");

WriteLiteral("><img");

WriteAttribute("src", Tuple.Create(" src=\"", 9455), Tuple.Create("\"", 9504)
, Tuple.Create(Tuple.Create("", 9461), Tuple.Create<System.Object, System.Int32>(Href("~/Areas/Forum/Assets/Images/default-pic.jpg")
, 9461), false)
);

WriteLiteral(" alt=\"\"");

WriteLiteral(" title=\"\"");

WriteLiteral(" class=\"forum-display-block\"");

WriteLiteral(" /></a>\r\n                    </div>\r\n                    <div");

WriteLiteral(" class=\"forum-article-props forum-float-left\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"forum-article-title\"");

WriteLiteral(">\r\n                            <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" title=\"#\"");

WriteLiteral(" class=\"forum-item-classify\"");

WriteLiteral(">[技术分享]</a>\r\n                            <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" title=\"#\"");

WriteLiteral(" class=\"forum-item-title\"");

WriteLiteral(">百签软件（中山）有限公司国庆放假消息。</a>\r\n                        </div>\r\n                       " +
" <div");

WriteLiteral(" class=\"forum-article-pushinfo forum-clear-both\"");

WriteLiteral(">\r\n                            <span");

WriteLiteral(" class=\"forum-article-tip\"");

WriteLiteral(">发布者：</span><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"forum-article-info\"");

WriteLiteral(">百小僧</a> <span");

WriteLiteral(" class=\"forum-article-tip\"");

WriteLiteral(">2016-09-22，最后回复来自：</span><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"forum-article-info\"");

WriteLiteral(">百签软件</a>\r\n                            <div");

WriteLiteral(" class=\"forum-article-record forum-float-right\"");

WriteLiteral("><span");

WriteLiteral(" class=\"forum-iconfont icon-forum-chakan\"");

WriteLiteral(">9</span><span");

WriteLiteral(" class=\"forum-iconfont icon-forum-pinglun\"");

WriteLiteral(">5</span></div>\r\n                        </div>\r\n                    </div>\r\n    " +
"            </div>\r\n                <div");

WriteLiteral(" class=\"forum-article-item forum-clear-both forum-auto-height\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"forum-article-member forum-float-left\"");

WriteLiteral(">\r\n                        <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" title=\"\"");

WriteLiteral(" class=\"forum-display-block\"");

WriteLiteral("><img");

WriteAttribute("src", Tuple.Create(" src=\"", 10760), Tuple.Create("\"", 10809)
, Tuple.Create(Tuple.Create("", 10766), Tuple.Create<System.Object, System.Int32>(Href("~/Areas/Forum/Assets/Images/default-pic.jpg")
, 10766), false)
);

WriteLiteral(" alt=\"\"");

WriteLiteral(" title=\"\"");

WriteLiteral(" class=\"forum-display-block\"");

WriteLiteral(" /></a>\r\n                    </div>\r\n                    <div");

WriteLiteral(" class=\"forum-article-props forum-float-left\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"forum-article-title\"");

WriteLiteral(">\r\n                            <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" title=\"#\"");

WriteLiteral(" class=\"forum-item-classify\"");

WriteLiteral(">[技术分享]</a>\r\n                            <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" title=\"#\"");

WriteLiteral(" class=\"forum-item-title\"");

WriteLiteral(">百签软件（中山）有限公司国庆放假消息。</a>\r\n                        </div>\r\n                       " +
" <div");

WriteLiteral(" class=\"forum-article-pushinfo forum-clear-both\"");

WriteLiteral(">\r\n                            <span");

WriteLiteral(" class=\"forum-article-tip\"");

WriteLiteral(">发布者：</span><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"forum-article-info\"");

WriteLiteral(">百小僧</a> <span");

WriteLiteral(" class=\"forum-article-tip\"");

WriteLiteral(">2016-09-22，最后回复来自：</span><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"forum-article-info\"");

WriteLiteral(">百签软件</a>\r\n                            <div");

WriteLiteral(" class=\"forum-article-record forum-float-right\"");

WriteLiteral("><span");

WriteLiteral(" class=\"forum-iconfont icon-forum-chakan\"");

WriteLiteral(">9</span><span");

WriteLiteral(" class=\"forum-iconfont icon-forum-pinglun\"");

WriteLiteral(">5</span></div>\r\n                        </div>\r\n                    </div>\r\n    " +
"            </div>\r\n                <div");

WriteLiteral(" class=\"forum-article-item forum-clear-both forum-auto-height\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"forum-article-member forum-float-left\"");

WriteLiteral(">\r\n                        <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" title=\"\"");

WriteLiteral(" class=\"forum-display-block\"");

WriteLiteral("><img");

WriteAttribute("src", Tuple.Create(" src=\"", 12065), Tuple.Create("\"", 12114)
, Tuple.Create(Tuple.Create("", 12071), Tuple.Create<System.Object, System.Int32>(Href("~/Areas/Forum/Assets/Images/default-pic.jpg")
, 12071), false)
);

WriteLiteral(" alt=\"\"");

WriteLiteral(" title=\"\"");

WriteLiteral(" class=\"forum-display-block\"");

WriteLiteral(" /></a>\r\n                    </div>\r\n                    <div");

WriteLiteral(" class=\"forum-article-props forum-float-left\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"forum-article-title\"");

WriteLiteral(">\r\n                            <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" title=\"#\"");

WriteLiteral(" class=\"forum-item-classify\"");

WriteLiteral(">[技术分享]</a>\r\n                            <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" title=\"#\"");

WriteLiteral(" class=\"forum-item-title\"");

WriteLiteral(">百签软件（中山）有限公司国庆放假消息。</a>\r\n                        </div>\r\n                       " +
" <div");

WriteLiteral(" class=\"forum-article-pushinfo forum-clear-both\"");

WriteLiteral(">\r\n                            <span");

WriteLiteral(" class=\"forum-article-tip\"");

WriteLiteral(">发布者：</span><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"forum-article-info\"");

WriteLiteral(">百小僧</a> <span");

WriteLiteral(" class=\"forum-article-tip\"");

WriteLiteral(">2016-09-22，最后回复来自：</span><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"forum-article-info\"");

WriteLiteral(">百签软件</a>\r\n                            <div");

WriteLiteral(" class=\"forum-article-record forum-float-right\"");

WriteLiteral("><span");

WriteLiteral(" class=\"forum-iconfont icon-forum-chakan\"");

WriteLiteral(">9</span><span");

WriteLiteral(" class=\"forum-iconfont icon-forum-pinglun\"");

WriteLiteral(">5</span></div>\r\n                        </div>\r\n                    </div>\r\n    " +
"            </div>\r\n                <div");

WriteLiteral(" class=\"forum-article-item forum-clear-both forum-auto-height\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"forum-article-member forum-float-left\"");

WriteLiteral(">\r\n                        <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" title=\"\"");

WriteLiteral(" class=\"forum-display-block\"");

WriteLiteral("><img");

WriteAttribute("src", Tuple.Create(" src=\"", 13370), Tuple.Create("\"", 13419)
, Tuple.Create(Tuple.Create("", 13376), Tuple.Create<System.Object, System.Int32>(Href("~/Areas/Forum/Assets/Images/default-pic.jpg")
, 13376), false)
);

WriteLiteral(" alt=\"\"");

WriteLiteral(" title=\"\"");

WriteLiteral(" class=\"forum-display-block\"");

WriteLiteral(" /></a>\r\n                    </div>\r\n                    <div");

WriteLiteral(" class=\"forum-article-props forum-float-left\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"forum-article-title\"");

WriteLiteral(">\r\n                            <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" title=\"#\"");

WriteLiteral(" class=\"forum-item-classify\"");

WriteLiteral(">[技术分享]</a>\r\n                            <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" title=\"#\"");

WriteLiteral(" class=\"forum-item-title\"");

WriteLiteral(">百签软件（中山）有限公司国庆放假消息。</a>\r\n                        </div>\r\n                       " +
" <div");

WriteLiteral(" class=\"forum-article-pushinfo forum-clear-both\"");

WriteLiteral(">\r\n                            <span");

WriteLiteral(" class=\"forum-article-tip\"");

WriteLiteral(">发布者：</span><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"forum-article-info\"");

WriteLiteral(">百小僧</a> <span");

WriteLiteral(" class=\"forum-article-tip\"");

WriteLiteral(">2016-09-22，最后回复来自：</span><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"forum-article-info\"");

WriteLiteral(">百签软件</a>\r\n                            <div");

WriteLiteral(" class=\"forum-article-record forum-float-right\"");

WriteLiteral("><span");

WriteLiteral(" class=\"forum-iconfont icon-forum-chakan\"");

WriteLiteral(">9</span><span");

WriteLiteral(" class=\"forum-iconfont icon-forum-pinglun\"");

WriteLiteral(">5</span></div>\r\n                        </div>\r\n                    </div>\r\n    " +
"            </div>\r\n                <div");

WriteLiteral(" class=\"forum-article-item forum-clear-both forum-auto-height\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"forum-article-member forum-float-left\"");

WriteLiteral(">\r\n                        <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" title=\"\"");

WriteLiteral(" class=\"forum-display-block\"");

WriteLiteral("><img");

WriteAttribute("src", Tuple.Create(" src=\"", 14675), Tuple.Create("\"", 14724)
, Tuple.Create(Tuple.Create("", 14681), Tuple.Create<System.Object, System.Int32>(Href("~/Areas/Forum/Assets/Images/default-pic.jpg")
, 14681), false)
);

WriteLiteral(" alt=\"\"");

WriteLiteral(" title=\"\"");

WriteLiteral(" class=\"forum-display-block\"");

WriteLiteral(" /></a>\r\n                    </div>\r\n                    <div");

WriteLiteral(" class=\"forum-article-props forum-float-left\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"forum-article-title\"");

WriteLiteral(">\r\n                            <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" title=\"#\"");

WriteLiteral(" class=\"forum-item-classify\"");

WriteLiteral(">[技术分享]</a>\r\n                            <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" title=\"#\"");

WriteLiteral(" class=\"forum-item-title\"");

WriteLiteral(">百签软件（中山）有限公司国庆放假消息。</a>\r\n                        </div>\r\n                       " +
" <div");

WriteLiteral(" class=\"forum-article-pushinfo forum-clear-both\"");

WriteLiteral(">\r\n                            <span");

WriteLiteral(" class=\"forum-article-tip\"");

WriteLiteral(">发布者：</span><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"forum-article-info\"");

WriteLiteral(">百小僧</a> <span");

WriteLiteral(" class=\"forum-article-tip\"");

WriteLiteral(">2016-09-22，最后回复来自：</span><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"forum-article-info\"");

WriteLiteral(">百签软件</a>\r\n                            <div");

WriteLiteral(" class=\"forum-article-record forum-float-right\"");

WriteLiteral("><span");

WriteLiteral(" class=\"forum-iconfont icon-forum-chakan\"");

WriteLiteral(">9</span><span");

WriteLiteral(" class=\"forum-iconfont icon-forum-pinglun\"");

WriteLiteral(">5</span></div>\r\n                        </div>\r\n                    </div>\r\n    " +
"            </div>\r\n                <div");

WriteLiteral(" class=\"forum-article-item forum-clear-both forum-auto-height\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"forum-article-member forum-float-left\"");

WriteLiteral(">\r\n                        <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" title=\"\"");

WriteLiteral(" class=\"forum-display-block\"");

WriteLiteral("><img");

WriteAttribute("src", Tuple.Create(" src=\"", 15980), Tuple.Create("\"", 16029)
, Tuple.Create(Tuple.Create("", 15986), Tuple.Create<System.Object, System.Int32>(Href("~/Areas/Forum/Assets/Images/default-pic.jpg")
, 15986), false)
);

WriteLiteral(" alt=\"\"");

WriteLiteral(" title=\"\"");

WriteLiteral(" class=\"forum-display-block\"");

WriteLiteral(" /></a>\r\n                    </div>\r\n                    <div");

WriteLiteral(" class=\"forum-article-props forum-float-left\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"forum-article-title\"");

WriteLiteral(">\r\n                            <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" title=\"#\"");

WriteLiteral(" class=\"forum-item-classify\"");

WriteLiteral(">[技术分享]</a>\r\n                            <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" title=\"#\"");

WriteLiteral(" class=\"forum-item-title\"");

WriteLiteral(">百签软件（中山）有限公司国庆放假消息。</a>\r\n                        </div>\r\n                       " +
" <div");

WriteLiteral(" class=\"forum-article-pushinfo forum-clear-both\"");

WriteLiteral(">\r\n                            <span");

WriteLiteral(" class=\"forum-article-tip\"");

WriteLiteral(">发布者：</span><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"forum-article-info\"");

WriteLiteral(">百小僧</a> <span");

WriteLiteral(" class=\"forum-article-tip\"");

WriteLiteral(">2016-09-22，最后回复来自：</span><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"forum-article-info\"");

WriteLiteral(">百签软件</a>\r\n                            <div");

WriteLiteral(" class=\"forum-article-record forum-float-right\"");

WriteLiteral("><span");

WriteLiteral(" class=\"forum-iconfont icon-forum-chakan\"");

WriteLiteral(">9</span><span");

WriteLiteral(" class=\"forum-iconfont icon-forum-pinglun\"");

WriteLiteral(">5</span></div>\r\n                        </div>\r\n                    </div>\r\n    " +
"            </div>\r\n                <div");

WriteLiteral(" class=\"forum-article-item forum-clear-both forum-auto-height\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"forum-article-member forum-float-left\"");

WriteLiteral(">\r\n                        <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" title=\"\"");

WriteLiteral(" class=\"forum-display-block\"");

WriteLiteral("><img");

WriteAttribute("src", Tuple.Create(" src=\"", 17285), Tuple.Create("\"", 17334)
, Tuple.Create(Tuple.Create("", 17291), Tuple.Create<System.Object, System.Int32>(Href("~/Areas/Forum/Assets/Images/default-pic.jpg")
, 17291), false)
);

WriteLiteral(" alt=\"\"");

WriteLiteral(" title=\"\"");

WriteLiteral(" class=\"forum-display-block\"");

WriteLiteral(" /></a>\r\n                    </div>\r\n                    <div");

WriteLiteral(" class=\"forum-article-props forum-float-left\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"forum-article-title\"");

WriteLiteral(">\r\n                            <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" title=\"#\"");

WriteLiteral(" class=\"forum-item-classify\"");

WriteLiteral(">[技术分享]</a>\r\n                            <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" title=\"#\"");

WriteLiteral(" class=\"forum-item-title\"");

WriteLiteral(">百签软件（中山）有限公司国庆放假消息。</a>\r\n                        </div>\r\n                       " +
" <div");

WriteLiteral(" class=\"forum-article-pushinfo forum-clear-both\"");

WriteLiteral(">\r\n                            <span");

WriteLiteral(" class=\"forum-article-tip\"");

WriteLiteral(">发布者：</span><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"forum-article-info\"");

WriteLiteral(">百小僧</a> <span");

WriteLiteral(" class=\"forum-article-tip\"");

WriteLiteral(">2016-09-22，最后回复来自：</span><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"forum-article-info\"");

WriteLiteral(">百签软件</a>\r\n                            <div");

WriteLiteral(" class=\"forum-article-record forum-float-right\"");

WriteLiteral("><span");

WriteLiteral(" class=\"forum-iconfont icon-forum-chakan\"");

WriteLiteral(">9</span><span");

WriteLiteral(" class=\"forum-iconfont icon-forum-pinglun\"");

WriteLiteral(">5</span></div>\r\n                        </div>\r\n                    </div>\r\n    " +
"            </div>\r\n            </div>\r\n        </div>\r\n        <div");

WriteLiteral(" id=\"forum-others\"");

WriteLiteral(" class=\"forum-float-right\"");

WriteLiteral("></div>\r\n    </div>\r\n</div>");

        }
    }
}
#pragma warning restore 1591
