#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Monk;
    using Monk.Areas.Backend.ViewModels;
    using Monk.Utils;
    using Monk.ViewModels;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Backend/Views/Cache/Detail.cshtml")]
    public partial class _Areas_Backend_Views_Cache_Detail_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Areas_Backend_Views_Cache_Detail_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 2 "..\..\Areas\Backend\Views\Cache\Detail.cshtml"
  
    ViewBag.Title = "查看缓存";
    Layout = "~/Areas/Backend/Views/Shared/_Detail.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

DefineSection("crumbs", () => {

WriteLiteral("\r\n    <label");

WriteLiteral(" class=\"backend-crumbs-separator\"");

WriteLiteral(">/</label>\r\n    <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" title=\"数据管理\"");

WriteLiteral(">数据管理</a>\r\n    <label");

WriteLiteral(" class=\"backend-crumbs-separator\"");

WriteLiteral(">/</label>\r\n    <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" title=\"缓存管理\"");

WriteLiteral(">缓存管理</a>\r\n    <label");

WriteLiteral(" class=\"backend-crumbs-separator\"");

WriteLiteral(">/</label>\r\n    <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" title=\"程序缓存\"");

WriteLiteral(">程序缓存</a>\r\n    <label");

WriteLiteral(" class=\"backend-crumbs-separator\"");

WriteLiteral(">/</label>\r\n    <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" title=\"查看缓存\"");

WriteLiteral(">查看缓存</a>\r\n");

});

WriteLiteral("\r\n<div");

WriteLiteral(" class=\"monk-form-item\"");

WriteLiteral(">\r\n    <label");

WriteLiteral(" for=\"\"");

WriteLiteral(" class=\"monk-form-label\"");

WriteLiteral(">缓存Key</label>\r\n    <div");

WriteLiteral(" class=\"monk-form-wrap monk-form-detail-wrap monk-full\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 21 "..\..\Areas\Backend\Views\Cache\Detail.cshtml"
   Write(ViewBag.Key);

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n</div>\r\n<div");

WriteLiteral(" class=\"monk-form-item\"");

WriteLiteral(">\r\n    <label");

WriteLiteral(" for=\"\"");

WriteLiteral(" class=\"monk-form-label\"");

WriteLiteral(">缓存Value</label>\r\n    <div");

WriteLiteral(" class=\"monk-form-wrap monk-form-code-wrap monk-full\"");

WriteLiteral(">\r\n        <pre");

WriteLiteral(" class=\"monk-code\"");

WriteLiteral(" data-language=\"JSON\"");

WriteLiteral(">");

            
            #line 27 "..\..\Areas\Backend\Views\Cache\Detail.cshtml"
                                               Write(StringHelper.ConvertJsonString(ViewBag.Value.ToString()));

            
            #line default
            #line hidden
WriteLiteral("</pre>\r\n    </div>\r\n</div>\r\n\r\n");

DefineSection("operate", () => {

WriteLiteral("\r\n    <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"monk-input-button alizarin\"");

WriteLiteral(" onclick=\"deletes();\"");

WriteLiteral(">删除记录</a>\r\n    <input");

WriteLiteral(" type=\"reset\"");

WriteLiteral(" class=\"monk-input-button peterRiver\"");

WriteAttribute("onclick", Tuple.Create(" onclick=\"", 1148), Tuple.Create("\"", 1213)
, Tuple.Create(Tuple.Create("", 1158), Tuple.Create("window.location.href", 1158), true)
, Tuple.Create(Tuple.Create(" ", 1178), Tuple.Create("=", 1179), true)
, Tuple.Create(Tuple.Create(" ", 1180), Tuple.Create("\'", 1181), true)
            
            #line 33 "..\..\Areas\Backend\Views\Cache\Detail.cshtml"
              , Tuple.Create(Tuple.Create("", 1182), Tuple.Create<System.Object, System.Int32>(Url.Action("Select","Cache")
            
            #line default
            #line hidden
, 1182), false)
, Tuple.Create(Tuple.Create("", 1211), Tuple.Create("\';", 1211), true)
);

WriteLiteral(" va");

WriteLiteral(" value=\"返回列表\"");

WriteLiteral(">\r\n    <input");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"monk-input-button orange monk-form-previous\"");

WriteLiteral(" value=\"返回前页\"");

WriteLiteral(" onclick=\"history.go(-1);\"");

WriteLiteral(">\r\n");

});

WriteLiteral("\r\n");

DefineSection("foot", () => {

WriteLiteral("\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n        function deletes() {\r\n            backend.confirm(\"删除该缓存会导致数据重新加载，您确定要" +
"执行此操作吗？\", null, function (index) {\r\n                backend.post(\"");

            
            #line 41 "..\..\Areas\Backend\Views\Cache\Detail.cshtml"
                         Write(Url.Action("Delete","Cache",new { }));

            
            #line default
            #line hidden
WriteLiteral("\", { ids: \"");

            
            #line 41 "..\..\Areas\Backend\Views\Cache\Detail.cshtml"
                                                                         Write(ViewBag.Key);

            
            #line default
            #line hidden
WriteLiteral("\" }, function (data) {\r\n                    window.location.href = \"");

            
            #line 42 "..\..\Areas\Backend\Views\Cache\Detail.cshtml"
                                       Write(Url.Action("Select", "Cache"));

            
            #line default
            #line hidden
WriteLiteral("\";\r\n                });\r\n            });\r\n        }\r\n    </script>\r\n");

});

        }
    }
}
#pragma warning restore 1591
