#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Monk;
    using Monk.Areas.Backend.ViewModels;
    using Monk.Utils;
    using Monk.ViewModels;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Backend/Views/Cache/Select.cshtml")]
    public partial class _Areas_Backend_Views_Cache_Select_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Areas_Backend_Views_Cache_Select_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Areas\Backend\Views\Cache\Select.cshtml"
  
    ViewBag.Title = "登录日志";
    Layout = "~/Areas/Backend/Views/Shared/_ListNoPage.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

DefineSection("crumbs", () => {

WriteLiteral("\r\n    <label");

WriteLiteral(" class=\"backend-crumbs-separator\"");

WriteLiteral(">/</label>\r\n    <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" title=\"数据管理\"");

WriteLiteral(">数据管理</a>\r\n    <label");

WriteLiteral(" class=\"backend-crumbs-separator\"");

WriteLiteral(">/</label>\r\n    <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" title=\"缓存管理\"");

WriteLiteral(">缓存管理</a>\r\n    <label");

WriteLiteral(" class=\"backend-crumbs-separator\"");

WriteLiteral(">/</label>\r\n    <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" title=\"程序缓存\"");

WriteLiteral(">程序缓存</a>\r\n    <label");

WriteLiteral(" class=\"backend-crumbs-separator\"");

WriteLiteral(">/</label>\r\n    <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" title=\"缓存列表\"");

WriteLiteral(">缓存列表</a>\r\n");

});

WriteLiteral("\r\n");

DefineSection("buttons", () => {

WriteLiteral("\r\n    <span");

WriteLiteral(" class=\"list-btn\"");

WriteLiteral(" onclick=\"backend.checkall(this);\"");

WriteLiteral("><i");

WriteLiteral(" class=\"monk-iconfont icon-backend-quanxuan\"");

WriteLiteral("></i><label>全选</label></span>\r\n    <span");

WriteLiteral(" class=\"list-btn\"");

WriteLiteral(" onclick=\"detail(this);\"");

WriteLiteral("><i");

WriteLiteral(" class=\"monk-iconfont icon-backend-details\"");

WriteLiteral("></i><label>查看</label></span>\r\n    <span");

WriteLiteral(" class=\"list-btn\"");

WriteLiteral(" onclick=\"deletes(this);\"");

WriteLiteral("><i");

WriteLiteral(" class=\"monk-iconfont icon-backend-delete\"");

WriteLiteral("></i><label>删除</label></span>\r\n    <span");

WriteLiteral(" class=\"list-btn float-right search-btn\"");

WriteLiteral(" onclick=\"backend.openSearch()\"");

WriteLiteral("><i");

WriteLiteral(" class=\"monk-iconfont icon-backend-search-list\"");

WriteLiteral("></i><label>搜索</label></span>\r\n");

});

WriteLiteral("\r\n<div");

WriteLiteral(" class=\"monk-table\"");

WriteLiteral(">\r\n    <table>\r\n        <thead>\r\n            <tr>\r\n                <th");

WriteLiteral(" align=\"center\"");

WriteLiteral(" class=\"monk-table-status\"");

WriteLiteral(">\r\n                    选择\r\n                </th>\r\n                <th");

WriteLiteral(" align=\"left\"");

WriteLiteral(">\r\n                    缓存Key\r\n                </th>\r\n            </tr>\r\n        <" +
"/thead>\r\n        <tbody></tbody>\r\n        <tfoot>\r\n        </tfoot>\r\n    </table" +
">\r\n</div>\r\n\r\n");

DefineSection("foot", () => {

WriteLiteral("\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n        function detail() {\r\n            var ids = backend.getCheckIds();\r\n   " +
"         if (ids.length == 1) {\r\n                backend.postLocation(\"");

            
            #line 47 "..\..\Areas\Backend\Views\Cache\Select.cshtml"
                                 Write(Url.Action("Detail","Cache",new { }));

            
            #line default
            #line hidden
WriteLiteral(@"/"", { id: ids[0] })
            }
            else {
                backend.Tip(""只能选择一条数据进行操作"");
            }
        }

        function deletes() {
            var ids = backend.getCheckIds();
            if (ids.length < 1) {
                backend.Tip(""至少选择一条进行操作"");
            }
            else {
                backend.confirm(""删除该缓存会导致数据重新加载，您确定要执行此操作吗？"", null, function (index) {
                    backend.post(""");

            
            #line 61 "..\..\Areas\Backend\Views\Cache\Select.cshtml"
                             Write(Url.Action("Delete","Cache",new { }));

            
            #line default
            #line hidden
WriteLiteral("\", { ids: ids.toString() }, function (data) {\r\n                        backend.ge" +
"t(\"");

            
            #line 62 "..\..\Areas\Backend\Views\Cache\Select.cshtml"
                                Write(Url.Action("RuntimeCache", "Cache"));

            
            #line default
            #line hidden
WriteLiteral(@""", {}, function (data) {
                            var html = render(data);
                            $("".monk-table table tbody"").html(html);
                        });
                    });
                });
            }
        }
    </script>
    <script");

WriteLiteral(" type=\"text/html\"");

WriteLiteral(" id=\"tpl\"");

WriteLiteral(@">
        <% for(var i=0;i < data.length;i++){ %>
        <tr>
            <td class=""monk-td-radio"">
                <span class=""monk-iconfont icon-backend-checkbox list-radio"" data-id=""<%=data[i].Current.Key%>""></span>
            </td>
            <td>
                <%=data[i].Current.Key %>
            </td>
        </tr>
        <% } %>
    </script>
    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n        var render = monk.tppl(document.getElementById(\"tpl\").innerHTML);\r\n   " +
"     $(function () {\r\n            backend.get(\"");

            
            #line 86 "..\..\Areas\Backend\Views\Cache\Select.cshtml"
                    Write(Url.Action("RuntimeCache", "Cache"));

            
            #line default
            #line hidden
WriteLiteral("\", {}, function (data) {\r\n                var html = render(data);\r\n             " +
"   $(\".monk-table table tbody\").html(html);\r\n            });\r\n        });\r\n    <" +
"/script>\r\n");

});

        }
    }
}
#pragma warning restore 1591
